### ISSUE TITLE
Error adding ruleset

### ISSUE THREAD

**Issue by DragoNico10** [Flutterish/Hitokori#28]
Every time I enter Osu!lazer this message appears:
[error]: Failed to add ruleset osu.Game.Rulesets.Hitokori, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
I tried replacing the file with the latest one, but nothing works.
Does anyone know how to solve this?

**Comment by Flutterish** [comment]
osu!lazer made a change which made some rulesets incompatible. [0.18.13](https://github.com/Flutterish/Hitokori/releases/tag/0.18.13-2021.12.06) works with the newest version.

**Comment by DragoNico10** [comment]
Thanks!
