### ISSUE TITLE
error in open osu!lazer

### ISSUE THREAD

**Issue by RafaelARRA11** [Flutterish/Hitokori#29]
i have installed 2 latest versions of Hitokori but came this error
![imagem_2022-02-12_131255](https://user-images.githubusercontent.com/99550396/153718988-5af53951-19dd-47f7-9503-48807a02fbb0.png)
i have osu! 2022.205.0-lazer

**Comment by anton-exe** [comment]
[In 2022.205.0 an attribute was renamed](https://github.com/ppy/osu/wiki/Breaking-Changes#20222050) which just needs a simple find + replace to fix according to the page.

**Comment by anton-exe** [comment]
I made a fork and changed what _I Think_ is the right things but I have no clue how to get the external libraries you need to compile to test if it works.

**Comment by Elabar** [comment]
Got it in my [fork](https://github.com/Elabar/Hitokori/tree/bump-osu-version)
You can go ahead and compile from my fork for now or use the one I compiled here
[hitokori-205-fix.zip](https://github.com/Flutterish/Hitokori/files/8078448/hitokori-205-fix.zip)

I have also created a PR to fix this #30

**Comment by Flutterish** [comment]
thank you, I've merged it and released an update
