### ISSUE TITLE
Error adding ruleset

### ISSUE THREAD

**Issue by androidu93** [Flutterish/Hitokori#31]
Hello, each time I try to add the ruleset, an error appears. Sorry if I have bad English.

**Comment by Flutterish** [comment]
[Hitokori 0.18.5](https://github.com/Flutterish/Hitokori/releases/tag/0.18.15-2022.02.16) was updated for lazer 2022.216 and still works with the newest version (2022.226). Please make sure your version of hito and lazer are both up to date.

**Comment by androidu93** [comment]
hello, Hitokori and osu!lazer are up to date. This message appears.

**Comment by androidu93** [comment]
![IMG_20220302_153350.jpg](https://user-images.githubusercontent.com/72980282/156382734-07c88a5f-b833-47c4-af45-590ba402937b.jpg)

**Comment by Flutterish** [comment]
You don't have to upload the file to your drive, you can upload them by dragging them to the comment box here.
I've requested access to the file you sent - you didn't make it publicly shared.

**Comment by androidu93** [comment]
Excuse me, I didn't pay attention, the link works now.

**Comment by androidu93** [comment]
Excuse me, I didn't pay attention, the link works now.

**Comment by Flutterish** [comment]
`Environment: Android`?
I don't believe custom rulesets in form of `.dll` work for mobile devices, they need to be bundled with the `.apk` to work. Even if they work, hito runs net5/6 while the app you seem to be running uses net4 (and I think mobile in general runs net standard 2.1).

Sorry, but I can't really help further. This is something that the lazer team will have to implement in the future. At some point mobile lazer will run net 6 and either you will be able to use the dlls or hito will be bundled with an unoffical apk which I will mention at a given release.
