### ISSUE TITLE
Ruleset won't load

### ISSUE THREAD

**Issue by richardscull** [Flutterish/Hitokori#39]
![image](https://user-images.githubusercontent.com/106016833/200169958-ec691b15-4a0f-4fb2-9587-9c09eae771e8.png)

Downloaded latest (0.18.21 to be clear) release and got this error, could be copy of #38, but im not sure. 
Version of osu!: 2022.1101.0-lazer.

**Comment by Flutterish** [comment]
Fixed in 0.18.22
