### ISSUE TITLE
The mod doesnt work

### ISSUE THREAD

**Issue by HaKey213** [Flutterish/Hitokori#40]
I downloaded the latest version of the mod and placed it in the ruleset folder of osu but when I launch my game it says that the mod couldnt be load and to check if the mod has an update even if I have the latest version

**Comment by Zazalng** [comment]
I fork myself release it playable (kinda)

**Comment by Zazalng** [comment]
> mine's didn't work fix this _bug_ please.

did you download release from my fork? if you download in this build it doesn't update so it won't work

**Comment by Flutterish** [comment]
Sorry, I updated the ruleset. It should work now.
