### ISSUE TITLE
The game crashed Once i Played a BeatMap with Autoplay.

### ISSUE THREAD

**Issue by PLGGitHub1** [Flutterish/Hitokori#47]

**Comment by Flutterish** [comment]
Should be fixed in 0.18.25

**Comment by murryguy** [comment]
> Should be fixed in 0.18.25

but older versions autoupdate😭😭😭😭😭😭😭

**Comment by Flutterish** [comment]
0.18.25 is the hitokori version, not osu version. rulesets do not autoupdate.
