### ISSUE TITLE
Game crashed caused by Hitokori and unexpected behavior with some beatmaps

### ISSUE THREAD

**Issue by heerxingen** [Flutterish/Hitokori#48]

**Comment by heerxingen** [comment]
whopps I accidentally clicked save
Here's what I wanted to say:
The ruleset says the tutorial is rated '0.0' for some reason, and when I tried to play the beatmap, osu! just crashed. I have no idea why and osu! doesn't seems to know lol
the beatmap is the 'new beginnings', and the file isn't corrupted.

**Comment by LJW21-GitHub** [comment]
Same goes with Android version of lazer. Except there were no 0.0* bug. Just a crash.

**Comment by Flutterish** [comment]
Should be fixed in 0.18.25
